import { useEffect, useMemo, useState } from 'react'
import { useLocation } from 'react-router-dom'
import { hubSpotObjectLabel, listOf, messageOf, parseHubSpotContext, pasApi } from '../../api/client'

const D={surface:'#fff',border:'#D6E5F1',text:'#173042',sub:'#5F778C',bg:'#EEF6FB',teal:'#3D9CA2',orange:'#F7761F',green:'#0FA372',red:'#E25555',amber:'#F3A52E'}
const input:React.CSSProperties={width:'100%',boxSizing:'border-box',padding:'8px 11px',borderRadius:7,border:`1px solid ${D.border}`,fontSize:12,color:D.text,background:'#fff'}
const btn=(color:string):React.CSSProperties=>({padding:'8px 14px',borderRadius:7,border:0,background:color,color:'#fff',fontSize:12,fontWeight:700,cursor:'pointer'})
function value(p:any,...keys:string[]){for(const k of keys)if(p?.[k]!==undefined&&p?.[k]!==null)return p[k];return null}
function policyId(p:any){return String(value(p,'policy_id','id')||'')}
function money(v:any,c='USD'){const n=Number(v);return Number.isFinite(n)?n.toLocaleString('en-US',{style:'currency',currency:c}):'—'}
function date(v:any){return v?new Date(v).toLocaleDateString():'—'}
function Badge({status}:{status:any}){const s=String(status||'UNKNOWN').toUpperCase();const c=s.includes('ISSUED')||s.includes('ACTIVE')||s.includes('REINSTATED')?D.green:s.includes('CANCEL')?D.red:s.includes('ENDORSE')?D.teal:D.amber;return <span style={{fontSize:10,fontWeight:700,padding:'3px 8px',borderRadius:10,color:c,background:`${c}18`,border:`1px solid ${c}44`}}>{s}</span>}
function Notice({text,danger=false}:{text:string;danger?:boolean}){return <div style={{background:danger?'#FFF1F1':'#FFF6ED',border:`1px solid ${danger?D.red:D.orange}55`,borderLeft:`4px solid ${danger?D.red:D.orange}`,color:danger?'#9B2C2C':'#98440E',borderRadius:8,padding:'10px 13px',fontSize:12,marginBottom:14}}>{text}</div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section style={{background:D.surface,border:`1px solid ${D.border}`,borderRadius:10,overflow:'hidden'}}><div style={{padding:'9px 15px',background:'#F7FAFC',borderBottom:`1px solid ${D.border}`,fontSize:11,fontWeight:700,color:D.sub,textTransform:'uppercase'}}>{title}</div><div style={{padding:'5px 15px'}}>{children}</div></section>}
function Row({label,value:v}:{label:string;value:any}){return <div style={{display:'flex',justifyContent:'space-between',gap:15,padding:'9px 0',borderBottom:`1px solid ${D.bg}`,fontSize:12}}><span style={{color:D.sub}}>{label}</span><strong style={{color:D.text,textAlign:'right'}}>{v??'—'}</strong></div>}
function RecordList({rows,empty,render}:{rows:any[];empty:string;render:(row:any)=>React.ReactNode}){return <section style={{background:D.surface,border:`1px solid ${D.border}`,borderRadius:10,overflow:'hidden'}}>{rows.length===0?<div style={{padding:40,textAlign:'center',color:D.sub}}>{empty}</div>:rows.map((row,i)=><div key={row.id||row.transaction_id||i} style={{padding:'12px 16px',borderBottom:`1px solid ${D.border}`,display:'grid',gap:4,fontSize:12,color:D.text}}>{render(row)}</div>)}</section>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.45)',display:'grid',placeItems:'center',zIndex:1000}} onClick={close}><div onClick={e=>e.stopPropagation()} style={{width:500,maxWidth:'92vw',background:'#fff',borderRadius:14,boxShadow:'0 20px 60px rgba(0,0,0,.25)',overflow:'hidden'}}><div style={{padding:'15px 19px',borderBottom:`1px solid ${D.border}`,display:'flex',justifyContent:'space-between'}}><strong style={{color:D.text}}>{title}</strong><button onClick={close} style={{border:0,background:'none',cursor:'pointer'}}>✕</button></div><div style={{padding:19}}>{children}</div></div></div>}

type Action='endorse'|'cancel'|'reinstate'|null
type Coverage={code:string;limit:string;deductible:string;status:string}
type PolicyTab='details'|'payments'|'claims'|'notifications'|'transactions'|'documents'|'renewal'
export default function PoliciesPage(){
 const location=useLocation();const [policies,setPolicies]=useState<any[]>([]);const [selected,setSelected]=useState<any>(null);const [details,setDetails]=useState<any>(null);const [tab,setTab]=useState<PolicyTab>('details');const [tabRows,setTabRows]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [tabLoading,setTabLoading]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');const [filters,setFilters]=useState({status:'',product:''});const [action,setAction]=useState<Action>(null);const [busy,setBusy]=useState(false);const [reason,setReason]=useState('');const [coverages,setCoverages]=useState<Coverage[]>([]);const [payment,setPayment]=useState({amount:'',payment_method:'card',reference:''});const [claim,setClaim]=useState({loss_date:new Date().toISOString().slice(0,10),loss_type:'',description:'',reserve_amount:'0'});const [hubspotRecord,setHubspotRecord]=useState<any>(null);const [hubspotStatus,setHubspotStatus]=useState('');const [hubspotError,setHubspotError]=useState('')
 const parsedHubspot=useMemo(()=>parseHubSpotContext(location.search),[location.search]);const hubspotIdentity=parsedHubspot.context;const hasHubspotPolicyWorkflow=!!hubspotIdentity&&['company','ticket'].includes(hubspotIdentity.objectType)
 async function load(){setLoading(true);setError('');try{setPolicies(listOf(await pasApi.policies(),'policies'))}catch(e){setPolicies([]);setError(messageOf(e,'Native policies could not be loaded. No fallback data is shown.'))}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);useEffect(()=>{setFilters(f=>({...f,status:new URLSearchParams(location.search).get('status')||''}))},[location.search])
 async function fetchTabRows(p:any,next:PolicyTab){const id=policyId(p);const body=next==='payments'?await pasApi.payments(id):next==='claims'?await pasApi.claims(id):next==='notifications'?await pasApi.notifications(id):next==='transactions'?await pasApi.transactions(id):next==='renewal'?await pasApi.renewals(id):await pasApi.versions(id);setTabRows(listOf(body,next))}
 async function open(p:any,initialTab:PolicyTab='details'){setSelected(p);setDetails(p);setTab(initialTab);setTabRows([]);setError('');setSuccess('');const id=policyId(p);if(!id)return;setTabLoading(initialTab!=='details'&&initialTab!=='documents');try{const detail=await pasApi.policy(id);setDetails(detail);setSelected(detail);if(initialTab!=='details'&&initialTab!=='documents')await fetchTabRows(detail,initialTab)}catch(e){setError(messageOf(e,initialTab==='details'?'Policy detail could not be loaded.':`Policy ${initialTab} could not be loaded.`))}finally{setTabLoading(false)}}
 useEffect(()=>{let cancelled=false;setHubspotRecord(null);setHubspotStatus('');setHubspotError('');if(parsedHubspot.error){setHubspotError(parsedHubspot.error);return}if(!hubspotIdentity)return;if(!hasHubspotPolicyWorkflow){setHubspotError(`HubSpot ${hubSpotObjectLabel(hubspotIdentity.objectType)} context cannot be opened in the policy workflow.`);return}setHubspotStatus(`Resolving HubSpot ${hubspotIdentity.objectType} ${hubspotIdentity.objectId}…`);pasApi.hubspotContext(hubspotIdentity).then(async context=>{if(cancelled)return;setHubspotRecord(context);if(context?.policy?.id){await open(context.policy,hubspotIdentity.objectType==='ticket'?'claims':'details');if(cancelled)return;setHubspotStatus(hubspotIdentity.objectType==='ticket'?`Ticket ${hubspotIdentity.objectId} is linked to policy ${context.policy.policy_number}. Claims and servicing are ready.`:`Company ${hubspotIdentity.objectId} portfolio is linked to policy ${context.policy.policy_number}.`)}else{setHubspotStatus(hubspotIdentity.objectType==='ticket'?`Ticket ${hubspotIdentity.objectId} is not linked to a policy. Open the correct policy, then link it to start servicing or a claim.`:`Company ${hubspotIdentity.objectId} has no linked policy portfolio. Open the correct policy, then link it deliberately.`)}}).catch(e=>{if(!cancelled){setHubspotStatus('');setHubspotError(messageOf(e,`HubSpot ${hubspotIdentity.objectType} context could not be loaded.`))}});return()=>{cancelled=true}},[location.search])
 async function refreshCurrent(){const id=policyId(details||selected);await load();if(id){try{const p=await pasApi.policy(id);setDetails(p);setSelected(p)}catch{/* list refresh remains authoritative */}}}
 function existingCoverages(p:any):Coverage[]{const raw=value(p,'coverages','coverage')||[];return Array.isArray(raw)&&raw.length?raw.map((c:any)=>({code:String(c.code||''),limit:String(c.limit||''),deductible:String(c.deductible||0),status:String(c.status||'issued').toLowerCase()})):[{code:'',limit:'',deductible:'0',status:'issued'}]}
 function begin(a:Action){setError('');setSuccess('');setReason('');if(a==='endorse')setCoverages(existingCoverages(details||selected));setAction(a)}
 async function submitAction(e:React.FormEvent){e.preventDefault();if(!selected||!action)return;const id=policyId(details||selected);if(!id){setError('This policy has no native policy_id; lifecycle action cannot be sent.');return}setBusy(true);setError('');try{if(action==='endorse'){const payload=coverages.map(c=>({code:c.code.trim(),limit:Number(c.limit),deductible:Number(c.deductible||0),status:c.status}));if(payload.some(c=>!c.code||!Number.isFinite(c.limit)||c.limit<=0))throw new Error('Every coverage needs a code and a limit greater than zero.');await pasApi.endorse({policy_id:id,coverages:payload})}else if(action==='cancel'){if(!reason.trim())throw new Error('Cancellation reason is required.');await pasApi.cancel({policy_id:id,reason:reason.trim()})}else await pasApi.reinstate({policy_id:id});setSuccess(`${action[0].toUpperCase()+action.slice(1)} completed by the native Rust PAS.`);setAction(null);await refreshCurrent()}catch(e){setError(messageOf(e,`${action} failed.`))}finally{setBusy(false)}}
 async function loadTab(next:PolicyTab){if(!selected)return;setTab(next);setError('');setTabRows([]);if(next==='details'||next==='documents')return;setTabLoading(true);try{await fetchTabRows(selected,next)}catch(e){setError(messageOf(e,`Policy ${next} could not be loaded.`))}finally{setTabLoading(false)}}
 async function linkHubspotPolicy(){if(!hubspotIdentity||!hasHubspotPolicyWorkflow||!selected)return;const p=details||selected;const id=policyId(p);if(!id){setError('This policy has no native policy_id and cannot be linked.');return}setBusy(true);setError('');try{const context=await pasApi.linkHubspotContext(hubspotIdentity,{customer_id:value(p,'customer_id','customerId')||hubspotRecord?.customer?.id||null,quote_id:value(p,'quote_id','quoteId')||hubspotRecord?.quote?.id||null,policy_id:id});setHubspotRecord(context);if(hubspotIdentity.objectType==='ticket'){setHubspotStatus(`Ticket ${hubspotIdentity.objectId} is linked to policy ${value(p,'policy_number','policyNumber','number')||id}. Claims and servicing are ready.`);await loadTab('claims')}else setHubspotStatus(`Company ${hubspotIdentity.objectId} portfolio is linked to policy ${value(p,'policy_number','policyNumber','number')||id}.`)}catch(e){setError(messageOf(e,`The policy could not be linked to this HubSpot ${hubspotIdentity.objectType}.`))}finally{setBusy(false)}}
 async function recordPayment(e:React.FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setError('');try{await pasApi.createPayment(policyId(selected),{amount:Number(payment.amount),payment_method:payment.payment_method,reference:payment.reference||null});setPayment({amount:'',payment_method:'card',reference:''});setSuccess('Payment recorded.');await loadTab('payments')}catch(e){setError(messageOf(e,'Payment could not be recorded.'))}finally{setBusy(false)}}
 async function reportClaim(e:React.FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setError('');try{await pasApi.createClaim(policyId(selected),{...claim,reserve_amount:Number(claim.reserve_amount)});setClaim({loss_date:new Date().toISOString().slice(0,10),loss_type:'',description:'',reserve_amount:'0'});setSuccess('Claim reported.');await loadTab('claims')}catch(e){setError(messageOf(e,'Claim could not be reported.'))}finally{setBusy(false)}}
 async function startRenewal(){if(!selected)return;setBusy(true);setError('');try{const renewal=await pasApi.createRenewal(policyId(selected));setSuccess(`Renewal quote ${renewal.renewal_quote_id} created.`);await loadTab('renewal')}catch(e){setError(messageOf(e,'Renewal quote could not be created.'))}finally{setBusy(false)}}
 async function download(){if(!selected)return;try{const id=policyId(selected);const blob=await pasApi.document(id);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`policy-${id}.pdf`;a.click();URL.revokeObjectURL(url)}catch(e){setError(messageOf(e,'Policy document could not be downloaded.'))}}
 const products=useMemo(()=>[...new Set(policies.map(p=>String(value(p,'productName','product_name','product','product_id')||'')).filter(Boolean))],[policies]);const shown=policies.filter(p=>(!filters.status||String(value(p,'status','state')||'').toUpperCase()===filters.status)&&(!filters.product||String(value(p,'productName','product_name','product','product_id')||'')===filters.product))
 if(selected){const p=details||selected;const number=value(p,'policyNumber','policy_number','number','id');const status=String(value(p,'status','state')||'').toLowerCase();const premium=value(p,'premiumAmount','totalPremium','premium');const canEndorse=['active','issued','endorsed'].includes(status);const canCancel=['active','issued','endorsed'].includes(status);const canReinstate=status==='cancelled'||status==='canceled';const canLinkHubspot=hasHubspotPolicyWorkflow&&!!hubspotRecord&&!hubspotRecord.policy;return <div style={{maxWidth:1100,margin:'0 auto'}}><button onClick={()=>{setSelected(null);setDetails(null)}} style={{border:0,background:'none',color:D.teal,padding:0,marginBottom:15,cursor:'pointer'}}>← Back to policies</button><div style={{display:'flex',justifyContent:'space-between',marginBottom:18}}><div><div style={{display:'flex',alignItems:'center',gap:9}}><h2 style={{margin:0,color:D.text,fontSize:20}}>{number}</h2><Badge status={status}/></div><p style={{margin:'4px 0 0',fontSize:12,color:D.sub}}>{value(p,'productName','product_name','product','product_id')||'Policy record'}</p></div><div style={{display:'flex',gap:7}}>{canLinkHubspot&&<button onClick={linkHubspotPolicy} disabled={busy} style={btn(D.orange)}>{busy?'Linking…':hubspotIdentity?.objectType==='ticket'?'Link policy to ticket':'Link policy to company'}</button>}<button onClick={()=>begin('endorse')} disabled={!canEndorse} title={!canEndorse?'Not valid for current state':''} style={{...btn(D.teal),opacity:canEndorse?1:.45}}>Endorse</button><button onClick={()=>begin('cancel')} disabled={!canCancel} title={!canCancel?'Not valid for current state':''} style={{...btn(D.red),opacity:canCancel?1:.45}}>Cancel</button><button onClick={()=>begin('reinstate')} disabled={!canReinstate} title={!canReinstate?'Only cancelled policies can be reinstated':''} style={{...btn(D.green),opacity:canReinstate?1:.45}}>Reinstate</button></div></div>{hubspotError&&<Notice text={hubspotError} danger/>}{hubspotStatus&&<Notice text={hubspotStatus}/>} {error&&<Notice text={error} danger/>}{success&&<div style={{background:'#ECFDF5',border:'1px solid #A7F3D0',color:'#087A55',borderRadius:8,padding:'10px 13px',fontSize:12,marginBottom:14}}>{success}</div>}<div style={{display:'flex',borderBottom:`2px solid ${D.border}`,marginBottom:18,overflowX:'auto'}}>{[['details','Details'],['payments','Payments'],['claims','Claims'],['notifications','Notifications'],['transactions','Transactions'],['documents','Documents'],['renewal','Renewal']].map(([k,l])=><button key={k} onClick={()=>loadTab(k as PolicyTab)} style={{padding:'10px 15px',border:0,background:'transparent',color:tab===k?D.teal:D.sub,fontWeight:tab===k?700:500,borderBottom:tab===k?`2px solid ${D.teal}`:'2px solid transparent',marginBottom:-2,cursor:'pointer',whiteSpace:'nowrap'}}>{l}</button>)}</div>
{tab==='details'&&<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}><Section title="Policy"><Row label="Policy number" value={number}/><Row label="Native policy ID" value={policyId(p)||'—'}/><Row label="Status" value={status||'—'}/><Row label="Inception" value={date(value(p,'policyStartDate','startDate','start_date','inception_date','effective_date'))}/><Row label="Expiry" value={date(value(p,'policyEndDate','endDate','end_date','expiry_date'))}/></Section><Section title="Insured & premium"><Row label="Insured" value={value(p,'policyHolder','insured_name','customer_name','customerName')}/><Row label="Product" value={value(p,'productName','product_name','product','product_id')}/><Row label="Premium" value={money(premium,value(p,'currency')||'USD')}/><Row label="Created" value={date(value(p,'createdAt','created_at'))}/></Section></div>}
{tabLoading&&<section style={{background:D.surface,border:`1px solid ${D.border}`,borderRadius:10,padding:40,textAlign:'center',color:D.sub}}>Loading live policy records…</section>}
{tab==='payments'&&!tabLoading&&<div style={{display:'grid',gridTemplateColumns:'360px 1fr',gap:16}}><Section title="Record payment"><form onSubmit={recordPayment} style={{display:'grid',gap:10,padding:'10px 0'}}><input style={input} type="number" min="0.01" step="0.01" placeholder={`Amount (${value(p,'currency')||'USD'})`} value={payment.amount} onChange={e=>setPayment(x=>({...x,amount:e.target.value}))} required/><select style={input} value={payment.payment_method} onChange={e=>setPayment(x=>({...x,payment_method:e.target.value}))}><option value="card">Card</option><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="cheque">Cheque</option></select><input style={input} placeholder="Reference (optional)" value={payment.reference} onChange={e=>setPayment(x=>({...x,reference:e.target.value}))}/><button style={btn(D.teal)} disabled={busy}>{busy?'Recording…':'Record payment'}</button></form></Section><RecordList rows={tabRows} empty="No payments recorded." render={(r:any)=><><strong>{money(r.amount,r.currency)}</strong><span>{r.payment_method} · {r.status} · {date(r.received_at)}</span></>}/></div>}
{tab==='claims'&&!tabLoading&&<div style={{display:'grid',gridTemplateColumns:'360px 1fr',gap:16}}><Section title="Report claim"><form onSubmit={reportClaim} style={{display:'grid',gap:10,padding:'10px 0'}}><input style={input} type="date" value={claim.loss_date} onChange={e=>setClaim(x=>({...x,loss_date:e.target.value}))} required/><input style={input} placeholder="Loss type" value={claim.loss_type} onChange={e=>setClaim(x=>({...x,loss_type:e.target.value}))} required/><textarea style={{...input,minHeight:75}} placeholder="Description" value={claim.description} onChange={e=>setClaim(x=>({...x,description:e.target.value}))} required/><input style={input} type="number" min="0" step="0.01" placeholder="Initial reserve" value={claim.reserve_amount} onChange={e=>setClaim(x=>({...x,reserve_amount:e.target.value}))}/><button style={btn(D.orange)} disabled={busy}>{busy?'Reporting…':'Report claim'}</button></form></Section><RecordList rows={tabRows} empty="No claims reported." render={(r:any)=><><strong>{r.claim_number} · {r.loss_type}</strong><span>{r.status} · Loss {date(r.loss_date)} · Reserve {money(r.reserve_amount,r.currency)}</span></>}/></div>}
{tab==='notifications'&&!tabLoading&&<RecordList rows={tabRows} empty="No policy notifications yet." render={(r:any)=><><strong>{r.subject}</strong><span>{r.message} · {date(r.created_at)}</span></>}/>}
{tab==='transactions'&&!tabLoading&&<RecordList rows={tabRows} empty="No policy transactions yet." render={(r:any)=><><strong>{r.transaction_type} · {r.status}</strong><span>{money(r.amount,r.currency)} · {r.description} · {date(r.effective_at)}</span></>}/>}
{tab==='documents'&&<section style={{background:D.surface,border:`1px solid ${D.border}`,borderRadius:10,padding:24}}><button onClick={download} style={btn(D.teal)}>Download policy document</button><p style={{fontSize:11,color:D.sub}}>Generated by the native policy document endpoint.</p></section>}
{tab==='renewal'&&!tabLoading&&<div style={{display:'grid',gap:14}}><section style={{background:D.surface,border:`1px solid ${D.border}`,borderRadius:10,padding:20,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><strong style={{color:D.text}}>Policy renewal</strong><div style={{fontSize:11,color:D.sub,marginTop:4}}>Create a real renewal quote from this policy's customer, product, premium, currency, and coverage.</div></div><button onClick={startRenewal} style={btn(D.orange)} disabled={busy}>{busy?'Creating…':'Create renewal quote'}</button></section><RecordList rows={tabRows} empty="No renewal quotes created." render={(r:any)=><><strong>Quote {r.renewal_quote_id}</strong><span>{r.status} · Effective {date(r.effective_date)}</span></>}/></div>}
{action&&<Modal title={action==='endorse'?'Endorse Policy':action==='cancel'?'Cancel Policy':'Reinstate Policy'} close={()=>setAction(null)}><form onSubmit={submitAction}>{action==='endorse'&&<div style={{display:'grid',gap:10}}>{coverages.map((c,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'1.2fr 1fr 1fr',gap:8}}><input style={input} value={c.code} onChange={e=>setCoverages(x=>x.map((v,n)=>n===i?{...v,code:e.target.value}:v))} placeholder="Coverage code" required/><input style={input} type="number" min="1" value={c.limit} onChange={e=>setCoverages(x=>x.map((v,n)=>n===i?{...v,limit:e.target.value}:v))} placeholder="Limit" required/><input style={input} type="number" min="0" value={c.deductible} onChange={e=>setCoverages(x=>x.map((v,n)=>n===i?{...v,deductible:e.target.value}:v))} placeholder="Deductible"/></div>)}<button type="button" onClick={()=>setCoverages(x=>[...x,{code:'',limit:'',deductible:'0',status:'issued'}])} style={{...btn(D.teal),width:'fit-content'}}>+ Add coverage</button></div>}{action==='cancel'&&<label style={{display:'grid',gap:5,fontSize:12,fontWeight:700,color:D.sub}}>Reason<textarea style={{...input,minHeight:90}} value={reason} onChange={e=>setReason(e.target.value)} required/></label>}{action==='reinstate'&&<p style={{fontSize:13,color:D.text}}>Reinstate this cancelled policy through the native Rust PAS?</p>}<div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:16}}><button type="button" onClick={()=>setAction(null)} style={{padding:'8px 14px',borderRadius:7,border:`1px solid ${D.border}`,background:'#fff',color:D.sub,cursor:'pointer'}}>Back</button><button style={btn(action==='cancel'?D.red:action==='endorse'?D.teal:D.green)} disabled={busy}>{busy?'Submitting…':'Confirm'}</button></div></form></Modal>}</div>}
 return <div style={{maxWidth:1150,margin:'0 auto'}}><div style={{marginBottom:18}}><h2 style={{fontSize:20,color:D.text,margin:0}}>Policies</h2><p style={{fontSize:12,color:D.sub,margin:'4px 0 0'}}>{shown.length} live native policy record{shown.length===1?'':'s'}</p></div>{hubspotError&&<Notice text={hubspotError} danger/>}{hubspotStatus&&<Notice text={hubspotStatus}/>} {error&&<Notice text={error} danger/>}<div style={{display:'flex',gap:9,marginBottom:12}}><select style={input} value={filters.status} onChange={e=>setFilters(f=>({...f,status:e.target.value}))}><option value="">All statuses</option>{['BOUND','ISSUED','ACTIVE','ENDORSED','CANCELLED','REINSTATED'].map(x=><option key={x}>{x}</option>)}</select><select style={input} value={filters.product} onChange={e=>setFilters(f=>({...f,product:e.target.value}))}><option value="">All products</option>{products.map(x=><option key={x}>{x}</option>)}</select></div><section style={{background:D.surface,border:`1px solid ${D.border}`,borderRadius:12,overflow:'hidden'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr style={{background:'#F7FAFC'}}>{['Policy #','Insured','Product','Status','Inception','Expiry','Premium'].map(x=><th key={x} style={{padding:'10px 13px',textAlign:'left',fontSize:10,color:D.sub,textTransform:'uppercase'}}>{x}</th>)}</tr></thead><tbody>{loading&&<tr><td colSpan={7} style={{padding:40,textAlign:'center',color:D.sub}}>Loading native policies…</td></tr>}{!loading&&shown.length===0&&<tr><td colSpan={7} style={{padding:48,textAlign:'center',color:D.sub}}>No policies returned by the native backend.</td></tr>}{shown.map((p,i)=><tr key={policyId(p)||i} onClick={()=>open(p)} style={{borderTop:`1px solid ${D.border}`,cursor:'pointer'}}><td style={{padding:'12px 13px',fontWeight:700,color:D.text}}>{value(p,'policyNumber','policy_number','number','id')}</td><td style={{padding:'12px 13px',fontSize:12,color:D.text}}>{value(p,'policyHolder','insured_name','customer_name','customerName')||'—'}</td><td style={{padding:'12px 13px',fontSize:12,color:D.sub}}>{value(p,'productName','product_name','product','product_id')||'—'}</td><td style={{padding:'12px 13px'}}><Badge status={value(p,'status','state')}/></td><td style={{padding:'12px 13px',fontSize:12,color:D.sub}}>{date(value(p,'policyStartDate','startDate','start_date','inception_date','effective_date'))}</td><td style={{padding:'12px 13px',fontSize:12,color:D.sub}}>{date(value(p,'policyEndDate','endDate','end_date','expiry_date'))}</td><td style={{padding:'12px 13px',fontWeight:700,color:D.text}}>{money(value(p,'premiumAmount','totalPremium','premium'),value(p,'currency')||'USD')}</td></tr>)}</tbody></table></section></div>
}
