import { useEffect, useMemo, useState } from 'react'
import { useLocation } from 'react-router-dom'
import { isSkeleton, listOf, messageOf, pasApi, getCurrentUserId } from '../../api/client'

const D={navy:'#0D2B3D',surface:'#fff',border:'#D6E5F1',text:'#173042',sub:'#5F778C',bg:'#EEF6FB',teal:'#3D9CA2',orange:'#F7761F',green:'#0FA372',red:'#E25555',amber:'#F3A52E'}
const inp:React.CSSProperties={width:'100%',boxSizing:'border-box',padding:'8px 11px',borderRadius:7,border:`1px solid ${D.border}`,fontSize:13,color:D.text,background:'#fff'}
const button=(color:string):React.CSSProperties=>({padding:'9px 17px',borderRadius:8,border:0,background:color,color:'#fff',fontWeight:700,fontSize:13,cursor:'pointer'})
function Section({title,children}:{title:string;children:React.ReactNode}){return <section style={{background:D.surface,border:`1px solid ${D.border}`,borderRadius:10,overflow:'hidden'}}><div style={{padding:'9px 15px',background:'#F7FAFC',borderBottom:`1px solid ${D.border}`,fontSize:11,fontWeight:700,color:D.sub,textTransform:'uppercase'}}>{title}</div><div style={{padding:15,display:'grid',gap:11}}>{children}</div></section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{fontSize:12,fontWeight:600,color:D.sub,display:'grid',gap:5}}>{label}{children}</label>}
function money(v:any,c='USD'){const n=Number(v);return Number.isFinite(n)?n.toLocaleString('en-US',{style:'currency',currency:c||'USD'}):'—'}
function badge(s:any){const x=String(s||'').toUpperCase();const c=x.includes('BOUND')||x.includes('ISSUED')?D.green:x.includes('QUOTE')?D.teal:D.amber;return <span style={{fontSize:10,fontWeight:700,padding:'3px 8px',borderRadius:10,color:c,background:`${c}18`,border:`1px solid ${c}44`}}>{x||'UNKNOWN'}</span>}

type View='list'|'quick'|'full'|'detail'
export default function QuotesPage(){
 const location=useLocation(); const [view,setView]=useState<View>('list'); const [quotes,setQuotes]=useState<any[]>([]); const [products,setProducts]=useState<any[]>([]); const [customers,setCustomers]=useState<any[]>([]); const [selected,setSelected]=useState<any>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [showCustomer,setShowCustomer]=useState(false)
 const [form,setForm]=useState<any>({customer_id:'',product_id:'',state:'',coverage_amount:'',customer_age:'',vehicle_value:'',carrier_id:'sagesure_pas',registration:'',make:'',model:'',year:''}); const [estimate,setEstimate]=useState<any>(null); const [rating,setRating]=useState<any>(null); const [busy,setBusy]=useState(false)
 async function load(){setLoading(true);setError('');try{const [q,p,c]=await Promise.all([pasApi.quotes(),pasApi.products(),pasApi.customers()]);setQuotes(listOf(q,'quotes'));setProducts(listOf(p,'products'));setCustomers(listOf(c,'customers'))}catch(e){setError(messageOf(e,'Native quote data could not be loaded.'));setQuotes([])}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 useEffect(()=>{const v=new URLSearchParams(location.search).get('view');if(v==='quick')setView('quick');else if(v==='full')setView('full')},[location.search])
 const product=products.find(x=>x.id===form.product_id); const customerMap=useMemo(()=>new Map(customers.map(x=>[x.id,x.name])),[customers]); const productMap=useMemo(()=>new Map(products.map(x=>[x.id,x.name])),[products])
 function set(k:string,v:any){setForm((f:any)=>({...f,[k]:v}));setEstimate(null);setRating(null);setError('')}
 function pricingBody(){return {insurance_type:product?.insurance_type,country:customers.find((c:any)=>c.id===form.customer_id)?.country||'US',state_code:form.state||null,coverage_amount:Number(form.coverage_amount),customer_age:form.customer_age?Number(form.customer_age):null,vehicle_value:form.vehicle_value?Number(form.vehicle_value):null}}
 async function quick(e:React.FormEvent){e.preventDefault();if(!product){setError('Select a native product.');return}setBusy(true);setError('');try{setEstimate(await pasApi.estimate(pricingBody()))}catch(e){setError(messageOf(e,'Native pricing estimate failed.'))}finally{setBusy(false)}}
 async function full(e:React.FormEvent){e.preventDefault();if(!product){setError('Select a native product.');return}setBusy(true);setError('');setEstimate(null);setRating(null);try{const est=await pasApi.estimate(pricingBody());setEstimate(est);let rated:any;try{rated=await pasApi.rate({carrier_id:form.carrier_id,product_id:form.product_id,state:form.state,risk:{customer_id:form.customer_id,coverage_amount:Number(form.coverage_amount),customer_age:form.customer_age?Number(form.customer_age):null,vehicle_value:form.vehicle_value?Number(form.vehicle_value):null,vehicle:{registration:form.registration||null,make:form.make||null,model:form.model||null,year:form.year?Number(form.year):null},pricing:est}})}catch(e){if(isSkeleton(e)){setError('Quote stopped: native provider pas:skeleton:v1 returned 422 Not Supported. No quote was created.');return}throw e}setRating(rated);if(rated?.decision!=='quoted'){setError(`Quote stopped: rating decision was ${rated?.decision||'unavailable'}. No quote was created.`);return}const premium=rated?.premium?.final_premium??est?.final_premium;if(!Number.isFinite(Number(premium))){setError('Quote stopped: no usable premium was returned.');return}const created=await pasApi.createQuote({customer_id:form.customer_id,product_id:form.product_id,premium:Number(premium),currency:rated?.premium?.currency?.toUpperCase?.()||est?.currency||product.currency,coverage:{customer_id:form.customer_id,coverage_amount:Number(form.coverage_amount),state:form.state,vehicle_value:form.vehicle_value?Number(form.vehicle_value):null,rating:{decision:rated.decision,carrier:rated.carrier,provider:rated.provider}}});setSelected(created);setView('detail');await load()}catch(e){setError(messageOf(e,'Native quote flow failed. No successful transition is being shown.'))}finally{setBusy(false)}}
 async function bind(){if(!selected?.id)return;setBusy(true);setError('');try{const r=await pasApi.bind(selected.id);setSelected({...selected,...r,state:r?.state||'bound'});await load()}catch(e){setError(messageOf(e,'Bind failed.'))}finally{setBusy(false)}}
 async function issue(){if(!selected?.id)return;setBusy(true);setError('');try{const policy=await pasApi.issueQuote(selected.id);setSelected({...selected,state:'issued',issued_policy:policy});await load()}catch(e){setError(messageOf(e,'Issue failed. The quote must be bound first.'))}finally{setBusy(false)}}
 const title=view==='list'?'Quotes':view==='quick'?'Quick Quote':view==='full'?'Full Quote':'Quote Detail'
 return <div style={{maxWidth:1200,margin:'0 auto'}}>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:20}}><div>{view!=='list'&&<button onClick={()=>setView('list')} style={{border:0,background:'none',color:D.teal,padding:0,marginBottom:8,cursor:'pointer'}}>← Back to quotes</button>}<h2 style={{fontSize:20,color:D.text,margin:0}}>{title}</h2><p style={{fontSize:12,color:D.sub,margin:'4px 0 0'}}>Native Rust pricing, rating, quote, bind, and issue workflow</p></div>{view==='list'&&<div style={{display:'flex',gap:8}}><button style={{...button(D.surface),color:D.text,border:`1px solid ${D.border}`}} onClick={()=>setShowCustomer(true)}>Add Customer</button><button style={{...button(D.surface),color:D.text,border:`1px solid ${D.border}`}} onClick={()=>setView('quick')}>Quick Quote</button><button style={button(D.orange)} onClick={()=>setView('full')}>Full Quote</button></div>}</div>
  {error&&<div style={{background:'#FFF1F1',border:`1px solid ${D.red}55`,borderLeft:`4px solid ${D.red}`,color:'#9B2C2C',borderRadius:8,padding:'10px 13px',fontSize:12,marginBottom:14}}>{error}</div>}
  {view==='list'&&<section style={{background:D.surface,border:`1px solid ${D.border}`,borderRadius:12,overflow:'hidden'}}><div style={{padding:'12px 16px',borderBottom:`1px solid ${D.border}`,fontSize:12,color:D.sub}}>{quotes.length} quote{quotes.length===1?'':'s'} · live native records only</div><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr style={{background:'#F7FAFC'}}>{['Customer','Product','Status','Premium','Created'].map(x=><th key={x} style={{padding:'10px 14px',textAlign:'left',fontSize:10,color:D.sub,textTransform:'uppercase',letterSpacing:'.05em'}}>{x}</th>)}</tr></thead><tbody>{loading&&<tr><td colSpan={5} style={{padding:40,textAlign:'center',color:D.sub}}>Loading native quotes…</td></tr>}{!loading&&quotes.length===0&&<tr><td colSpan={5} style={{padding:48,textAlign:'center',color:D.sub}}>No quotes returned by the native backend.</td></tr>}{quotes.map(q=><tr key={q.id} onClick={()=>{setSelected(q);setView('detail')}} style={{borderTop:`1px solid ${D.border}`,cursor:'pointer'}}><td style={{padding:'12px 14px',fontSize:13,color:D.text}}>{customerMap.get(q.customer_id)||q.customer_id}</td><td style={{padding:'12px 14px',fontSize:13,color:D.sub}}>{productMap.get(q.product_id)||q.product_id}</td><td style={{padding:'12px 14px'}}>{badge(q.state||q.status)}</td><td style={{padding:'12px 14px',fontWeight:700,color:D.text}}>{money(q.premium,q.currency)}</td><td style={{padding:'12px 14px',fontSize:12,color:D.sub}}>{q.created_at?new Date(q.created_at).toLocaleDateString():'—'}</td></tr>)}</tbody></table></div></section>}
  {view==='quick'&&<form onSubmit={quick} style={{display:'grid',gridTemplateColumns:'420px 1fr',gap:18,alignItems:'start'}}><QuoteFields form={form} set={set} products={products} customers={customers} quick/><section style={{background:D.surface,border:`1px solid ${D.border}`,borderRadius:12,padding:22,minHeight:200}}>{estimate?<><div style={{fontSize:12,color:D.sub}}>Indicative price</div><div style={{fontSize:40,fontWeight:800,color:D.orange,margin:'8px 0'}}>{money(estimate.final_premium,estimate.currency)}</div><button type="button" style={button(D.orange)} onClick={()=>setView('full')}>Proceed to full quote →</button></>:<div style={{color:D.sub,fontSize:13,padding:40,textAlign:'center'}}>Select native customer and product, then request pricing.</div>}</section><button style={button(D.navy)} disabled={busy||!form.customer_id||!form.product_id}>{busy?'Calculating…':'Get indicative price'}</button></form>}
  {view==='full'&&<form onSubmit={full} style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:18,alignItems:'start'}}><QuoteFields form={form} set={set} products={products} customers={customers}/><div style={{display:'grid',gap:14}}><Section title="Rating"><Field label="Carrier ID"><input style={inp} value={form.carrier_id} onChange={e=>set('carrier_id',e.target.value)} required/></Field><div style={{fontSize:11,color:D.sub}}>Native pricing must succeed before PAS rating. Unsupported providers stop the flow; no quote is fabricated.</div></Section>{estimate&&<Section title="Pricing result"><div style={{fontSize:28,fontWeight:800,color:D.orange}}>{money(estimate.final_premium,estimate.currency)}</div></Section>}{rating&&<Section title="Rating result"><div style={{fontSize:13,color:D.text}}>Decision: <strong>{rating.decision}</strong></div></Section>}<button style={button(D.orange)} disabled={busy||!form.customer_id||!form.product_id||!form.coverage_amount}>{busy?'Running native quote flow…':'Rate and save quote'}</button></div></form>}
  {view==='detail'&&selected&&<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:18}}><Section title="Quote"><div style={{fontSize:18,fontWeight:700,color:D.text}}>{selected.id}</div><div>{badge(selected.state||selected.status)}</div><Field label="Customer"><div>{customerMap.get(selected.customer_id)||selected.customer_id||'—'}</div></Field><Field label="Product"><div>{productMap.get(selected.product_id)||selected.product_id||'—'}</div></Field></Section><Section title="Premium & actions"><div style={{fontSize:32,fontWeight:800,color:D.orange}}>{money(selected.premium,selected.currency)}</div><button onClick={bind} disabled={busy||['bound','issued'].includes(String(selected.state||selected.status).toLowerCase())} style={{...button(D.green),opacity:['bound','issued'].includes(String(selected.state||selected.status).toLowerCase())?.45:1}}>{busy?'Working…':'Bind quote'}</button><button onClick={issue} disabled={busy||String(selected.state||selected.status).toLowerCase()!=='bound'} title={String(selected.state||selected.status).toLowerCase()!=='bound'?'Bind the quote first':''} style={{...button(D.orange),opacity:String(selected.state||selected.status).toLowerCase()==='bound'?1:.45}}>Issue policy</button></Section></div>}
  {showCustomer&&<CustomerModal close={()=>setShowCustomer(false)} saved={async customer=>{setShowCustomer(false);await load();setForm((f:any)=>({...f,customer_id:customer.id}))}}/>}
 </div>
}

function CustomerModal({close,saved}:{close:()=>void;saved:(customer:any)=>void}){const [form,setForm]=useState({name:'',email:'',phone:'',country:'US',currency:'USD',address:''});const [busy,setBusy]=useState(false);const [error,setError]=useState('');async function submit(e:React.FormEvent){e.preventDefault();const user_id=getCurrentUserId();if(!user_id){setError('Authenticated user identity is unavailable. Sign in again.');return}setBusy(true);setError('');try{const customer=await pasApi.createCustomer({user_id,...form,currency:form.currency.toLowerCase(),address:form.address||null,national_id:null,national_id_type:null});saved(customer)}catch(e){setError(messageOf(e,'Customer creation failed.'))}finally{setBusy(false)}}return <div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.45)',display:'grid',placeItems:'center',zIndex:1000}} onClick={close}><form onSubmit={submit} onClick={e=>e.stopPropagation()} style={{width:500,maxWidth:'92vw',background:'#fff',borderRadius:14,overflow:'hidden',boxShadow:'0 20px 60px rgba(0,0,0,.25)'}}><div style={{padding:'15px 19px',borderBottom:`1px solid ${D.border}`,display:'flex',justifyContent:'space-between'}}><strong style={{color:D.text}}>Add Customer</strong><button type="button" onClick={close} style={{border:0,background:'none',cursor:'pointer'}}>✕</button></div><div style={{padding:19,display:'grid',gap:11}}>{error&&<div style={{background:'#FFF1F1',color:'#9B2C2C',padding:10,borderRadius:7,fontSize:12}}>{error}</div>}<input style={inp} placeholder="Full name" value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))} required/><input style={inp} type="email" placeholder="Email" value={form.email} onChange={e=>setForm(f=>({...f,email:e.target.value}))} required/><input style={inp} placeholder="Phone" value={form.phone} onChange={e=>setForm(f=>({...f,phone:e.target.value}))} required/><input style={inp} placeholder="Address" value={form.address} onChange={e=>setForm(f=>({...f,address:e.target.value}))}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><input style={inp} maxLength={2} placeholder="Country" value={form.country} onChange={e=>setForm(f=>({...f,country:e.target.value.toUpperCase()}))} required/><select style={inp} value={form.currency} onChange={e=>setForm(f=>({...f,currency:e.target.value}))}><option>USD</option><option>INR</option></select></div><div style={{display:'flex',justifyContent:'flex-end',gap:8}}><button type="button" onClick={close} style={{...button('#fff'),color:D.sub,border:`1px solid ${D.border}`}}>Cancel</button><button disabled={busy} style={button(D.orange)}>{busy?'Creating…':'Create Customer'}</button></div></div></form></div>}

function QuoteFields({form,set,products,customers,quick=false}:{form:any;set:(k:string,v:any)=>void;products:any[];customers:any[];quick?:boolean}){return <div style={{display:'grid',gap:14}}><Section title="Customer & product"><Field label="Existing customer"><select style={inp} value={form.customer_id} onChange={e=>set('customer_id',e.target.value)} required><option value="">Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} · {c.id}</option>)}</select></Field><Field label="Native product"><select style={inp} value={form.product_id} onChange={e=>set('product_id',e.target.value)} required><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.insurance_type}</option>)}</select></Field>{customers.length===0&&<div style={{fontSize:11,color:D.amber}}>No native customers are available. Customer creation remains a native API operation and is not simulated.</div>}</Section><Section title="Risk & cover"><Field label="State code"><input style={inp} maxLength={2} value={form.state} onChange={e=>set('state',e.target.value.toUpperCase())} placeholder="TX"/></Field><Field label="Coverage amount"><input style={inp} type="number" min="1" value={form.coverage_amount} onChange={e=>set('coverage_amount',e.target.value)} required/></Field><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><Field label="Customer age"><input style={inp} type="number" min="0" value={form.customer_age} onChange={e=>set('customer_age',e.target.value)}/></Field><Field label="Vehicle value"><input style={inp} type="number" min="0" value={form.vehicle_value} onChange={e=>set('vehicle_value',e.target.value)}/></Field></div>{!quick&&<><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><Field label="Registration"><input style={inp} value={form.registration} onChange={e=>set('registration',e.target.value)}/></Field><Field label="Year"><input style={inp} type="number" value={form.year} onChange={e=>set('year',e.target.value)}/></Field></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><Field label="Make"><input style={inp} value={form.make} onChange={e=>set('make',e.target.value)}/></Field><Field label="Model"><input style={inp} value={form.model} onChange={e=>set('model',e.target.value)}/></Field></div></>}</Section></div>}
